#!/bin/bash

# Detect source directory
# Thanks to http://stackoverflow.com/a/246128/2204144
source="$0"
while [ -h "${source}" ]; do
    dir="$( cd -P "$( dirname "${source}" )" && pwd )"
    source="$(readlink "${source}")"
done
directory="$( cd "$( dirname "${source}" )" && pwd )"

cd "${directory}"
python3 "${directory}/cli.py" $@
